version: '2.3'

services:
 app:
  image: portainer/portainer
  container_name: local-portainer
  ports:
  - "9000:9000"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - ./portainer_data:/data
